### PR TITLE
fix(metrics): bump opentelemetry dependenncies

### PR DESCRIPTION
**Pull request by liufuyang**
Move server.rpc.duration metric to server.rpc.duration_deprecated, as it is now included in the otelgrpc opentelemetry contrib package. A side effect of this is that we loose the status code attr.

Status on this can be tracked here:
open-telemetry/opentelemetry-go-contrib#2840

---

Basically, do this reverted https://github.com/einride/cloudrunner-go/pull/382 again as there has been a fix for the memory (infinite loop) issue https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/591

But we keep `rpc.server.duration_deprecated` metric for now and remove it later. Also allowing a comparison of our own metric implementation vs the [opentelemetry-go-contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2840) implementation

### CODE REVIEW

**Comment by ericwenn** [comment]
Why keep the previous metric under new name?

**Comment by liufuyang** [comment]
I want to compare whether they have differences as we have some alerts is using it and filtering on grpc status code and so on. If there does have some differences and we have difficulties updating the alerts, we might want to switch to our internal one for a while, and perhaps able to update the implementation on their side.

**Review by ericwenn — APPROVED** [review]

**Comment by liufuyang** [comment]
image
Looks like `rpc_grpc_status_code` can still be used but `rpc_grpc_code` will be missing.

**Comment by liufuyang** [comment]
The problem still exists... 

image

**Pull request merged**
