### PR TITLE
feat: add standard traceId log attribute

### PR DESCRIPTION
**Pull request by odsod**
Makes cross-project trace investigations easier in joined log buckets.

### CODE REVIEW

**Review by alethenorio — COMMENTED** [review]
Won't filtering on this only filter logs generated by the library's middleware and miss GCP own service logs? If that's the case would it not be potentially misleading to users?

The same result can be achieved using the `has` operator on the resource name field which will also include GCP own service logs. See https://cloud.google.com/logging/docs/view/logging-query-language#comparisons

**Comment by odsod** [comment]
@alethenorio I'm just moving this existing feature from one of our internal libraries, which is getting split up. I'm also happy to drop this functionality entirely. WDYT?

**Comment by alethenorio** [comment]
Not against have the field per se but just wondering whether enabling it might be counter productive in the end.

Giving it some more thought maybe being able to do filtering on the click of a button might be good for easy access to cross project logs and then if needed the user can drill down further.

**Review by alethenorio — APPROVED** [review]

**Comment by odsod** [comment]
@alethenorio I agree that it would be good to avoid depending on custom attributes! Let's discuss dropping it altogether at a guild meeting? In the meantime I added `Experimental` to the documentation to try and point out that we may remove this in the future.

**Comment by alethenorio** [comment]
Sounds like a good plan

**Pull request merged**
