### PR TITLE
feat(deps): bump all deps

### PR DESCRIPTION
**Pull request by odsod**

### CODE REVIEW

**Comment by DavyJ0nes** [comment]
Put up a PR to do that: https://github.com/einride/cloudrunner-go/pull/544

**Comment by DavyJ0nes** [comment]
we could also go to v1.21? I don't see any downside to that. What do you think @odsod ?

**Comment by odsod** [comment]
@DavyJ0nes Big +1 on that - see comment in other PR!

**Review by DavyJ0nes — APPROVED** [review]
nice!

**Pull request merged**
